language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: surge
  local_dir: build
  domain: harmonious-bushes.surge.sh
  skip_cleanup: true
  on:
    branch: master
